### ISSUE TITLE
we need a default 404 response for client and server

### ISSUE THREAD

**Issue by Jcroxford** [Jcroxford/grader-aide#16]
we need a default server 404 response outside of the basic one given by espress.

**Comment by Jcroxford** [comment]
### Todos
- [ ] create and wire up 404 page for vue spa
- [ ] setup 404 error response on the rest server. This specifically needs to be done for `/api` routes because default 404 response on the server will need to redirect to the vue app (i'll explain)
- [ ] setup default 404 response outside of `/api` routes. This response needs to just redirect to vue spa dist directory
