### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by Jcroxford** [Jcroxford/grader-aide#23]
we need to create client side authentication.

### Todos
- [x] admin authorization
- [x] user authorization
- [x] route guards for user auth
- [x] route guards for admin auth
- [x] setup auth via passport probably and bcryptjs for salting and hashing password
- [x] configure middleware in express server to perform server side auth
- [x] logout option on navbar when a user is already authenticated

to be continued? ......

**Comment by Jcroxford** [comment]
### thoughts
do we need a registration page?

eventually user has like a list of assignments n grades

**Comment by Jcroxford** [comment]
### Issues
design decision needs to be made to keep navbar reactive during localstorage state changes. Vuex might be the best route but we can also consider an event bus or some other alternative.

another idea I found to keep things simple though not great practice would be to check localstorage every time a route changes from our parent component and pass a prop to the navbar. [example](https://stackoverflow.com/questions/46402809/vuejs-event-on-route-change)

**Comment by Jcroxford** [comment]
went with watcher in navbar for the time being. Closing this issues because authentication is done as defined in checklist
