### ISSUE TITLE
Finish Rules design and functionality

### ISSUE THREAD

**Issue by Jcroxford** [Jcroxford/grader-aide#3]
### Todos
**editing**
- [x] edit button(s)
- [x] setup interface for editing one or multiple rules depending on how we do it
- [x] edit points for a rule
- [x] edit description for a rule
- [x] edit total points for an assignment

**add/remove rule**
- [x] figure out and implement id for a rule
- [x] implement being able to add 
- [x] implement removing a rule
- [x] implement stack order for removing a rule (so we can keep track of rules removed for undo op.)
- [x] implement undo operation for that re-adds rule after being deleted

**display**
- [x] shows 

### Design Dicussions
we still gotta nail this down 100% but right now what we discussed was using a modal with a list of editable rules. Do we still want to take this approach?

Individualize modal to comments and rules are have a set of both?

**Comment by harryt04** [comment]
rules complete
