### ISSUE TITLE
Milestone 2 EXTRAS

### ISSUE THREAD

**Issue by harryt04** [Jcroxford/grader-aide#30]
- [ ] UVU Bootstrap theme
- [ ] Nuxt (server rendering, SEO)
- [ ] Firebase (easy hosted document store)
- [ ] Cassandra
- [ ] Redis
- [ ] Neo4J
- [ ] SASS
- [ ] AWS
