### ISSUE TITLE
Comments basics

### ISSUE THREAD

**Issue by Jcroxford** [Jcroxford/grader-aide#4]
### Todos
**editing**
- [x] Edit button(s)
- [x] setup interface for editing one or multiple comments depending on how we do it.
- [x] edit description for a rule

**add/remove comment**
- [x] figure out and implementation id for a comment
- [x] implement being able to add comment
- [x] implement removing a comment
- [x] implement stack order for removing a comment (so we can keep track of comments removed for undo op.)
- [x] implement undo operation that re-adds comment after being deleted

**list selected comments**
- [x] register comments that are selected into a list that allows easy copy paste actions

### Design Dicussions
mostly same discussions as rules so far

**Comment by harryt04** [comment]
Complete
